In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import tarfile
import seaborn as sns 
import json
# Load the TSV file into a DataFrame
tsv_file_path = "data/MovieSummaries/movie.metadata.tsv"
df_movies = pd.read_csv(tsv_file_path, sep='\t')
new_column_names = [
    'WikipediaMovieID',
    'FreebaseMovieID',
    'MovieName',
    'MovieReleaseDate',
    'MovieBoxOfficeRevenue',
    'MovieRuntime',
    'MovieLanguages',
    'MovieCountries',
    'MovieGenres'
]

df_movies.columns = new_column_names

def get_first(mapping):
    mapping = json.loads(mapping)
    if mapping:
        return next(iter(mapping.values()))
    return None

def replace(text):
    return str(text).replace(" Language", "").replace(" language", "")
 
# Apply the function to get the first country name
df_movies['MovieCountries']= df_movies['MovieCountries'].apply(get_first)
df_movies['MovieLanguages']= df_movies['MovieLanguages'].apply(get_first)
df_movies['MovieLanguages']= df_movies['MovieLanguages'].apply(replace)

df_movies['MovieGenres']= df_movies['MovieGenres'].apply(get_first)

# Show the DataFrame

df_movies

,WikipediaMovieID,FreebaseMovieID,MovieName,MovieReleaseDate,MovieBoxOfficeRevenue,MovieRuntime,MovieLanguages,MovieCountries,MovieGenres
0,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,English,United States of America,Mystery
1,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,Norwegian,Norway,Crime Fiction
2,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,English,United Kingdom,Thriller
3,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,German,Germany,Drama
4,13696889,/m/03cfc81,The Gangsters,1913-05-29,NaN,35.0,Silent film,United States of America,Short Film
...,...,...,...,...,...,...,...,...,...
81735,35228177,/m/0j7hxnt,Mermaids: The Body Found,2011-03-19,NaN,120.0,English,United States of America,Drama
81736,34980460,/m/0g4pl34,Knuckle,2011-01-21,NaN,96.0,English,Ireland,Biographical film
81737,9971909,/m/02pygw1,Another Nice Mess,1972-09-22,NaN,66.0,English,United States of America,Satire
81738,913762,/m/03pcrp,The Super Dimension Fortress Macross II: Lover...,1992-05-21,NaN,150.0,Japanese,Japan,Science Fiction
81739,12476867,/m/02w7zz8,Spliced,2002,NaN,86.0,English,Canada,Thriller

In [2]:
summary_file_path = "data/MovieSummaries/plot_summaries.txt"
df_summary = pd.read_csv(summary_file_path, sep='\t', header = 0)
new_column_names = [
    'SummaryID',
    'Summary'
]

df_summary.columns = new_column_names
df_summary

       SummaryID                                            Summary
0       31186339  The nation of Panem consists of a wealthy Capi...
1       20663735  Poovalli Induchoodan  is sentenced for six yea...
2        2231378  The Lemon Drop Kid , a New York City swindler,...
3         595909  Seventh-day Adventist Church pastor Michael Ch...
4        5272176  The president is on his way to give a speech. ...
...          ...                                                ...
42297   34808485  The story is about Reema , a young Muslim scho...
42298    1096473  In 1928 Hollywood, director Leo Andreyev  look...
42299   35102018  American Luthier focuses on Randy Parsons’ tra...
42300    8628195  Abdur Rehman Khan , a middle-aged dry fruit se...
42301    6040782  1940 - Operation Dynamo has just taken place. ...

[42302 rows x 2 columns]

In [5]:
df_Movies = df_movies.merge(df_summary, left_on='WikipediaMovieID', right_on='SummaryID', how='outer')
df_Movies.dropna(subset=['MovieName'], inplace=True)
df_Movies

,WikipediaMovieID,FreebaseMovieID,MovieName,MovieReleaseDate,MovieBoxOfficeRevenue,MovieRuntime,MovieLanguages,MovieCountries,MovieGenres,SummaryID,Summary
0,3196793.0,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,English,United States of America,Mystery,NaN,NaN
1,28463795.0,/m/0crgdbh,Brun bitter,1988,NaN,83.0,Norwegian,Norway,Crime Fiction,NaN,NaN
2,9363483.0,/m/0285_cd,White Of The Eye,1987,NaN,110.0,English,United Kingdom,Thriller,9363483.0,A series of murders of rich young women throug...
3,261236.0,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,German,Germany,Drama,261236.0,"Eva, an upper class housewife, becomes frustra..."
4,13696889.0,/m/03cfc81,The Gangsters,1913-05-29,NaN,35.0,Silent film,United States of America,Short Film,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
81735,35228177.0,/m/0j7hxnt,Mermaids: The Body Found,2011-03-19,NaN,120.0,English,United States of America,Drama,35228177.0,Two former National Oceanic Atmospheric Admini...
81736,34980460.0,/m/0g4pl34,Knuckle,2011-01-21,NaN,96.0,English,Ireland,Biographical film,34980460.0,{{No plot}} This film follows 12 years in the ...
81737,9971909.0,/m/02pygw1,Another Nice Mess,1972-09-22,NaN,66.0,English,United States of America,Satire,NaN,NaN
81738,913762.0,/m/03pcrp,The Super Dimension Fortress Macross II: Lover...,1992-05-21,NaN,150.0,Japanese,Japan,Science Fiction,913762.0,"The story takes place in the year 2092,The Sup..."
81739,12476867.0,/m/02w7zz8,Spliced,2002,NaN,86.0,English,Canada,Thriller,12476867.0,The movie is about a teenage girl who loves ho...

In [9]:
titanic_movies = df_Movies[df_Movies['MovieName'] == 'Titanic']

for summary in titanic_movies['Summary']:
    print(summary)

The film opens with a proclamation to the White Star stockholders that the value of their stocks are falling. The president of White Star Line J. Bruce Ismay promises to reveal a secret during the maiden voyage of the Titanic that will change the fate of the stocks. He alone knows that the ship can break the world record in speed and that, he thinks, will raise the stock value  Ismay and the board of the White Star plan to lower the stocks by selling even their own stocks in order to buy them back at a lower price. They plan to buy them back just before the news about the record speed of the ship will be published to the press.  The issue of capitalism and the stock market plays a dominant role throughout the movie. The hero of the film is fictional German First Officer Herr Petersen (played by [[Hans Nielsen  on the ill-fated voyage of the British ocean liner RMS Titanic in 1912. He begs the ship's rich, snobbish and sleazy owners to slow down the ship's speed, but they refuse and the Titanic hits an iceberg and sinks. The passengers in first class are shown to be sleazy cowards while Petersen, his lover Sigrid Olinsky  who is unlike other first class passengers, and other German passengers in steerage are shown as brave and kind. Peterson manages to rescue many passengers, convince Sigrid to get into a lifeboat, and saves a young girl, who was obviously left to die in her cabin by an uncaring, callous British capitalist mother. In the ship's final death throes, Petersen leaps from the deck with the little girl still in his arms and is then pulled aboard Sigrid's lifeboat and they watch in horror as the Titanic plunges beneath the waves. The film ends with the British Inquiry into the disaster, where Peterson testifies against Bruce Ismay, condemning his actions, but Ismay is cleared of all charges and the blame is placed squarely on the deceased Captain Smith's shoulders. The epilogue states that "the deaths of 1,500 people remain un-atoned, forever a testament of Britain's endless quest for profit."
 In 1996, treasure hunter Brock Lovett and his team explore the wreck of RMS Titanic, searching for a valuable diamond necklace called the Heart of the Ocean. They recover Caledon "Cal" Hockley's safe, believing the necklace to be inside, but instead find a sketch of a nude woman wearing it, dated April 14, 1912, the night the Titanic sank. Hearing about the drawing, an elderly woman named Rose Dawson Calvert calls Lovett and claims that she is the woman depicted in the drawing. She and her granddaughter, Lizzy Calvert, visit him and his team on his salvage ship. When asked if she knows the whereabouts of the necklace, Rose recalls her time aboard the Titanic, revealing that she is Rose DeWitt Bukater, a passenger believed to have died in the sinking. She then begins her story as follows: In 1912, 17-year-old first class passenger Rose boards "Titanic" in Southampton with her fiancé Cal and her mother Ruth DeWitt Bukater. Ruth stresses the importance of Rose's engagement, as the marriage would solve the DeWitt Bukaters' secret financial problems. Distraught by her engagement, Rose considers suicide by jumping off the ship's stern; a drifter and artist named Jack Dawson stops her. Discovered with Jack on the stern, Rose tells Cal that she was looking over the ship's edge in curiosity and that Jack saved her from falling. Pressed, Jack confirms her account. Cal is at first aloof to Jack, but when Rose indicates that recognition is due, he offers him a small amount of money. After Rose mocks Cal for this, asking if her life means so little, he invites Jack to a first-class dinner the following night. Jack and Rose develop a tentative friendship, even though Cal and Ruth are wary of the young third-class man. Following the dinner that night, Rose secretly joins Jack at a party in the ship's third-class quarter. Because Cal and Ruth forbid her to see Jack, Rose attempts to rebuff Jack's continuing advances. She soon realizes, though, that she prefers him over Cal, and meets him at the bow of the ship during what turns out to be the Titanic{{'s}} final moments of daylight. They then go to Rose's stateroom, where she asks Jack to sketch her nude while wearing the Heart of the Ocean, Cal's engagement present to her. Afterward, the two evade Cal's bodyguard and make love inside a car in the ship's cargo hold. Going afterwards to the ship's forward well deck, they witness the ship's collision with an iceberg and overhear the ship's officers and designer outline its seriousness. Rose tells Jack that they should warn her mother and Cal. Cal discovers Jack's drawing and a mocking note from Rose in his safe along with the necklace. Furious, he has his bodyguard slip the necklace into Jack's coat pocket. Accused of stealing it, Jack is arrested, taken down to the Master-at-arms's office and handcuffed to a pipe. Cal puts the necklace in his coat. Rose runs away from Cal and her mother  and releases Jack. The ship then starts to launch flares in order to attract any nearby ships. Once Jack and Rose reach the deck, Cal and Jack persuade her to board another lifeboat, Cal claiming that he has arranged for himself and Jack to get off safely. After she boards, Cal tells Jack that the arrangement is only for himself. As Rose's boat lowers, she realizes that she cannot leave Jack, and jumps back on board the Titanic to reunite with him. Infuriated, Cal takes a pistol and chases them into the flooding first-class dining saloon. After exhausting his ammunition, Cal realizes to his chagrin that he gave his coat with the diamond to Rose. With the situation now dire, he returns to the boat deck and boards a lifeboat by pretending to look after a lost child. Jack and Rose return to the top deck. All lifeboats have departed and passengers are falling to their deaths as the stern rises out of the water. The ship breaks in half, and the stern side rises 90-degrees into the air. As it sinks, Jack and Rose ride the stern into the ocean. Jack helps Rose onto a wall panel only able to support one person's weight. Holding the panel's edge, he assures her she will die an old woman, warm in her bed. Meanwhile, Fifth Officer Harold Lowe has commandeered a lifeboat to search for survivors. Jack soon dies of hypothermia and Rose draws the attention of Lowe's boat, and is ultimately saved. Rose and the other survivors are taken by the RMS Carpathia to New York, where Rose gives her name as Rose Dawson. She hides from Cal on Carpathia{{'s}} deck as he searches for her. She learns later that he committed suicide after losing his fortune in the Wall Street Crash of 1929. Her story complete, Rose goes alone to the stern of Lovett's ship. There she takes out the Heart of the Ocean, which has been in her possession all along, and drops it into the ocean. While seemingly asleep in her bed, the photos on her dresser are a visual chronicle that she lived a free life inspired by Jack. The young Rose is then seen reuniting with Jack at the Grand Staircase of the RMS Titanic, applauded and congratulated by those who perished on the ship.
Titanic has three main story threads: *Isabella Paradine is traveling on the Titanic to join her husband after attending her aunt's funeral in England. On the Titanic, she meets Wynn Park, her former lover. She falls in love with him again, and after a brief affair, she sends her husband a wireless saying they cannot be together anymore . When the ship starts sinking, Isabella must reluctantly leaves Wynn when he forces her to board a lifeboat. As the boat is lowered, Isabella confesses a long kept secret that her daughter Claire is actually Wynn's. Later on board the RMS Carpathia she is grief-stricken when she finds Wynn's lifeless body on deck amongst other victims who have died of hypothermia, but luckily, when the Carpathia reaches New York she is reunited with her family, blissfully unaware of Isabella's tryst because the telegram was never sent out due to the sinking. *Also in first class is the Allison family, a real family who traveled on the Titanic, returning home to Montreal with their two small children and new nurse, Alice Cleaver. They gradually become wary and suspicious of her hysterical and neurotic behavior. Later on, a fellow maid asks her if she'd seen her in Cairo the previous month, but soon realizes that she remembers her from the highly publicized trial where Alice was accused of throwing her baby off a train. When the Titanic starts sinking, Alice Cleaver panics and quickly boards a lifeboat with Trevor, the Allisons' infant son. The parents with their small daughter are unaware that the baby is safe and refuse to leave the ship without him, which in the end costs them their lives. *In third class, a young vagrant named Jamie Perse steals a ticket to get on board. He manages to become friends with one of the crewmen, Simon Doonan, who is also a robber, but later is revealed to be a much more violent and callous criminal than Jamie. The young man falls in love with Aase  Ludvigsen, a recent Christian convert and missionary. On the night of the sinking, Aase is raped and beaten by Doonan, causing her to lose her faith and will to live, but Jamie manages to get her into Isabella's boat, #14. Unbeknownst to them, Doonan also sneaked on board that same boat, disguised as an old woman. After the ship sinks, Aase is knocked off the lifeboat by Doonan after recognizing him and he attempts holding all the passengers in the boat hostage with a revolver, but Officer Lowe, who is in charge of the boat, hits Doonan in the head with a paddle, snapping his neck. Jamie himself manages to survive when he accidentally falls into one of the last lifeboats before the Titanic sinks and atones for his past life after he finds Aase in the makeshift hospital aboard the Carpathia. In the end, upon arriving in New York, the two plan to start a new life together.
Mrs Julia Sturges , who is at the time estranged from her husband Richard , is traveling first class on the RMS Titanic. Determined to remove her children from her husband Richard's "high society" world in Europe, Julia secretly takes their two children, 17-year-old Annette  and ten-year-old Norman , on the Titanic and plans to raise them in her hometown of Mackinac, Michigan. However, after he learns of her plans, Richard pays a premium to buy a steerage ticket from a Basque immigrant in hopes of intercepting them and taking the children back to Europe. Richard and Julia talk about the custody of Annette and Norman over their first dinner on board. Other passengers include a wealthy woman of working-class origins based on Molly Brown, Maude Young ; a social-climbing snob, Earl Meeker ; a 20-year-old Purdue University tennis player, Gifford Rogers , who falls in love with Annette Sturges; and a priest who has been suspended for alcoholism, George S. Healey . Julia realizes that Annette is old enough to make her own decisions and, therefore, may choose to return to Europe with her father, but she insists on maintaining custody of Norman. This angers Richard, and later, prior to dining at the captain's table, he aggressively confronts Julia. She then reveals to him that Norman is not his biological child but, rather, the result of a one-night stand she had after leaving a party where she was being belittled in the days before Richard had "made [her] over into [his] image." He agrees to relinquish custody of Norman , being cold and distant from them. Richard joins Maude, Earl, and George Widener in the lounge to play bridge with them. Norman tries to get Richard to play shuffleboard with him, but he yells at him, sending him away. Giff teaches Annette the "Navajo Rag," and she finds herself smitten with him. That night Giff, Annette, and a group of college students sing and play the piano in the dining room, and from a corner table, Captain Smith watches. Suddenly the lookout spots an iceberg, and although the crew tries to steer clear of danger, the ship is cut open by the iceberg. Julia and Norman are awakened by the crash and Annette tells them that the ship has hit an iceberg. Richard tells his family to dress warmly, but properly; then, they head outside. Richard and Julia have a tearful reconciliation on the boat deck, as he is putting Julia and the children in famous Lifeboat #6. Later, Norman gives up his seat in the full lifeboat so that a woman can be accommodated, and goes looking for his father. They reunite as the Titanic is in her final moments. Richard tells a passing steward that Norman is his 'son' and then tells the boy that he has been proud of him every day of his life and that he feels "tall as a mountain" standing by the boy's side. Then, they join the rest of the passengers and crew in singing the hymn "Nearer, My God, to Thee." The Titanic rises high in the air, explodes twice more, and rapidly sinks. Richard and Norman both drown. Giff Rogers falls into the ocean while trying to free a stuck lifeboat and is rescued by the passengers in Lifeboat #7. He survives. Meeker disguises himself as a woman and gains admittance to a lifeboat. He also survives, although Young recognizes him and calls him out in front of the other people in the lifeboat. George Healey tries to pull himself together as the ship is sinking, and goes below , joining crewmen who have been trapped in the engine room.

In [12]:
import spacy

# Load a pre-trained English language model
nlp = spacy.load("en_core_web_md")

# Assuming you have a DataFramedf_Movies with 'MovieName' and 'Summary' columns
df_Movies =df_Movies.dropna(subset=['Summary'])

# Define the reference text related to the "WAR" theme
reference_text = "war conflict battle military soldier"

# Create a list of similarity scores for each movie summary
similarity_scores = []

for summary in df_Movies['Summary']:
    doc = nlp(summary)
    reference_doc = nlp(reference_text)
    
    # Calculate the similarity score between the movie summary and the reference text
    similarity = doc.similarity(reference_doc)
    similarity_scores.append(similarity)

# Add similarity scores to the DataFramedf_Movies['SimilarityToWar'] = similarity_scores

# Select movies with a similarity score above 0.8
similar_movies =df_Movies[df_Movies['SimilarityToWar'] > 0.8]

# Print the similar movies
print(similar_movies[['MovieName', 'SimilarityToWar']])

KeyboardInterrupt:

In [14]:
import spacy
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Maxime\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Maxime\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Maxime\AppData\Roaming\nltk_data...

True

In [15]:
from tqdm import tqdm  # Import tqdm for the progress bar

In [22]:
war_words = ['War', 'war', 'Military conflict', 'military conflict', 'Armed conflict', 'armed conflict', 'Battle', 'battle', 'Combat', 'combat', 'Soldier', 'soldier', 'Veteran', 'veteran', 'Army', 'army', 'Navy', 'navy', 'Air Force', 'air force', 'Marine Corps', 'marine corps', 'Warzone', 'warzone', 'Battlefield', 'battlefield', 'Casualty', 'casualty', 'POW', 'pow', 'MIA', 'mia', 'Victory', 'victory', 'Defeat', 'defeat', 'Peacekeeping', 'peacekeeping', 'Imperialism', 'imperialism', 'Atrocities', 'atrocities', 'Antiwar', 'antiwar', 'Democracy', 'democracy', 'Freedom', 'freedom', 'Assassination', 'assassination', 'Hypocrisy', 'hypocrisy', 'Propaganda', 'propaganda', 'Nationalism', 'nationalism', 'Patriotism', 'patriotism', 'Trauma', 'trauma', 'Courage', 'courage', 'Sacrifice', 'sacrifice', 'Survival', 'survival', 'PTSD', 'ptsd', 'Homecoming', 'homecoming', 'Humanitarian', 'humanitarian', 'Intervention', 'intervention', 'Peace', 'peace', 'Nuclear war', 'nuclear war', 'Chemical warfare', 'chemical warfare', 'Biological warfare', 'biological warfare', 'Cyberwarfare', 'cyberwarfare', 'Espionage', 'espionage', 'Terrorism', 'terrorism', 'Insurgency', 'insurgency', 'Guerrilla warfare', 'guerrilla warfare', 'Proxy war', 'proxy war', 'Cold War', 'cold war', 'World War I', 'world war I', 'World War II', 'world war II', 'Korean War', 'korean war', 'Vietnam War', 'vietnam war', 'Gulf War', 'gulf war', 'Iraq War', 'iraq war', 'Afghanistan War', 'afghanistan war', 'Armistice', 'armistice', 'Bombing', 'bombing', 'Conscientious objector', 'conscientious objector', 'Draft', 'draft', 'Enemy', 'enemy', 'Front line', 'front line', 'Genocide', 'genocide', 'Hostage', 'hostage', 'Invasion', 'invasion', 'Jingoism', 'jingoism', 'Kamikaze', 'kamikaze', 'Landmine', 'landmine', 'Mobilization', 'mobilization', 'National security', 'national security', 'Occupation', 'occupation', 'Pacifism', 'pacifism', 'Quarantine', 'quarantine', 'Resistance', 'resistance', 'Sabotage', 'sabotage', 'Tank', 'tank', 'Uniform', 'uniform', 'Victory garden', 'victory garden', 'War crime', 'war crime', 'Xenophobia', 'xenophobia', 'Aerial warfare', 'aerial warfare', 'Amphibious warfare', 'amphibious warfare', 'Artillery', 'artillery', 'Biological agent', 'biological agent', 'Chemical agent', 'chemical agent', 'Civil war', 'civil war', 'Covert operation', 'covert operation', 'Cyberattack', 'cyberattack', 'Deception', 'deception', 'Diplomacy', 'diplomacy', 'Espionage', 'espionage', 'Firebombing', 'firebombing', 'Friendly fire', 'friendly fire', 'Gas attack', 'gas attack', 'Grenade', 'grenade', 'Helicopter', 'helicopter', 'Infantry', 'infantry', 'Intelligence', 'intelligence', 'Land warfare', 'land warfare', 'Machine gun', 'machine gun', 'Mercenary', 'mercenary', 'Missile', 'missile', 'Naval warfare', 'naval warfare', 'Nuclear weapon', 'nuclear weapon', 'Occupation', 'occupation', 'Paratrooper', 'paratrooper', 'Propaganda film', 'propaganda film', 'Radar', 'radar', 'Reconnaissance', 'reconnaissance', 'Siege', 'siege', 'Sniper', 'sniper', 'Submarine', 'submarine', 'Tank warfare', 'tank warfare', 'Trench warfare', 'trench warfare', 'War correspondent', 'war correspondent', 'War economy', 'war economy', 'War film', 'war film', 'War novel', 'war novel', 'War photography', 'war photography', 'War propaganda', 'war propaganda', 'War veteran', 'war veteran']

In [25]:
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

# Load your DataFrame
# Assuming you have a DataFrame named df_Movies with 'MovieName' and 'Summary' columns

# Remove NaN values in the 'Summary' column
df_Movies = df_Movies.dropna(subset=['Summary'])

reference_text = " ".join(war_words)

# Tokenize and preprocess the movie summaries
stop_words = set(nltk.corpus.stopwords.words('english'))

def preprocess_text(text):
    tokens = nltk.word_tokenize(text)
    tokens = [word.lower() for word in tokens if word.isalpha()]  # Remove punctuation
    tokens = [word for word in tokens if word not in stop_words]  # Remove stopwords
    return " ".join(tokens)

# Calculate TF-IDF scores for movie summaries
tfidf_vectorizer = TfidfVectorizer()

# Use tqdm to create a progress bar
pbar = tqdm(total=len(df_Movies), position=0, leave=True)
df_Movies['ProcessedSummary'] = ""

for i, row in df_Movies.iterrows():
    df_Movies.at[i, 'ProcessedSummary'] = preprocess_text(row['Summary'])
    pbar.update(1)

pbar.close()

# Calculate TF-IDF scores for processed movie summaries
tfidf_matrix = tfidf_vectorizer.fit_transform(df_Movies['ProcessedSummary'])
reference_vector = tfidf_vectorizer.transform([reference_text])
cosine_similarities = cosine_similarity(reference_vector, tfidf_matrix)

# Add similarity scores to the DataFrame
df_Movies['SimilarityToWar'] = cosine_similarities[0]

# Select movies with a similarity score above 0.8
similar_movies = df_Movies[df_Movies['SimilarityToWar'] > 0.8]

# Print the similar movies
print(similar_movies[['MovieName', 'SimilarityToWar']])

 10%|▉         | 4078/42202 [00:16<02:37, 242.66it/s]
 32%|███▏      | 13686/42202 [00:30<01:05, 438.45it/s]

In [19]:
similar_movies

Empty DataFrame
Columns: [WikipediaMovieID, FreebaseMovieID, MovieName, MovieReleaseDate, MovieBoxOfficeRevenue, MovieRuntime, MovieLanguages, MovieCountries, MovieGenres, SummaryID, Summary, CleanedSummary, ProcessedSummary, SimilarityToWar]
Index: []

In [16]:
# Load the English language model, NLTK stopwords, and create a WordNetLemmatizer instance
nlp = spacy.load("en_core_web_md")
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Assuming you have a DataFrame df_Movies with 'MovieName' and 'Summary' columns
df_Movies = df_Movies.dropna(subset=['Summary'])

# Define the reference text related to the "WAR" theme and tokenize it
reference_text = "war conflict battle military soldier"
reference_tokens = word_tokenize(reference_text)

# Create a function to preprocess and clean the text
def preprocess_text(text):
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words and word.isalpha()]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    cleaned_text = ' '.join(tokens)
    return cleaned_text

# Apply the preprocessing function to the 'Summary' column in your DataFrame
tqdm.pandas()  # Use tqdm's progress_apply for pandas Series
df_Movies['CleanedSummary'] = df_Movies['Summary'].progress_apply(preprocess_text)

# Create a list of similarity scores for each movie summary
similarity_scores = []

# Use tqdm to display a progress bar
for cleaned_summary in tqdm(df_Movies['CleanedSummary']):
    doc = nlp(cleaned_summary)
    reference_doc = nlp(" ".join(reference_tokens))
    
    # Calculate the similarity score between the movie summary and the reference text
    similarity = doc.similarity(reference_doc)
    similarity_scores.append(similarity)

# Add similarity scores to the DataFrame
df_Movies['SimilarityToWar'] = similarity_scores

# Select movies with a similarity score above 0.8
similar_movies = df_Movies[df_Movies['SimilarityToWar'] > 0.8]

# Print the similar movies
print(similar_movies[['MovieName', 'SimilarityToWar']])

100%|██████████| 42202/42202 [01:55<00:00, 365.98it/s]
 46%|████▌     | 19481/42202 [10:55<12:44, 29.71it/s]

KeyboardInterrupt:

In [ ]:
df_Movies.to_csv('MoviesWithSummaryAndWarSimilarity.txt', sep='\t', index=False)